# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ComputeSNN <- function(nn_ranked, prune) {
    .Call(`_SpatialCellChat_ComputeSNN`, nn_ranked, prune)
}

cpp_sum_layers <- function(matrices) {
    .Call(`_SpatialCellChat_cpp_sum_layers`, matrices)
}

